# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "wordy-ruby"
  s.version = "0.2.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bastien Vaucher - MagmaHQ"]
  s.date = "2012-04-18"
  s.description = "Ruby library to access the Wordy API"
  s.email = "bastien.vaucher@gmail.com"
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/wordy.rb",
    "lib/wordy/account.rb",
    "lib/wordy/cli.rb",
    "lib/wordy/job.rb",
    "rWordy.gemspec",
    "spec/spec_helper.rb",
    "spec/wordy/account_spec.rb",
    "spec/wordy/job_spec.rb",
    "wordy-ruby.gemspec",
    "wordy.gemspec"
  ]
  s.homepage = "http://github.com/bastien/wordy"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "Wordy API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.2.2"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.9.0"])
      s.add_development_dependency(%q<shoulda>, [">= 3.0.1"])
      s.add_development_dependency(%q<rspec>, [">= 2.9.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.2.2"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 3.2.2"])
      s.add_dependency(%q<bundler>, ["~> 1.1.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.9.0"])
      s.add_dependency(%q<shoulda>, [">= 3.0.1"])
      s.add_dependency(%q<rspec>, [">= 2.9.0"])
      s.add_dependency(%q<activesupport>, [">= 3.2.2"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 3.2.2"])
    s.add_dependency(%q<bundler>, ["~> 1.1.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.9.0"])
    s.add_dependency(%q<shoulda>, [">= 3.0.1"])
    s.add_dependency(%q<rspec>, [">= 2.9.0"])
    s.add_dependency(%q<activesupport>, [">= 3.2.2"])
  end
end

